import { ScrollView, StyleSheet, View } from "react-native";
import React from "react";
import ModalWrapper from "@/components/ModalWrapper";
import Header from "@/components/Header";
import BackButton from "@/components/BackButton";
import Typo from "@/components/Typo";
import { spacingX, spacingY } from "@/constants/theme";
import { useTheme } from "@/contexts/themeContext";

const TermsOfServiceModal = () => {
  const { colors } = useTheme();
  return (
    <ModalWrapper>
      <View style={styles.container}>
        <Header
          title="Terms of Service"
          leftIcon={<BackButton />}
          style={{ marginBottom: spacingY._10, marginTop: spacingY._10 }}
        />

        <ScrollView contentContainerStyle={styles.content}>
          <Typo size={15} color={colors.textLight} style={{ marginBottom: spacingY._10 }}>
            Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
          </Typo>

          <View style={styles.section}>
            <Typo size={18} fontWeight="700" color={colors.text}>
              1. Acceptance of Terms
            </Typo>
            <Typo size={14} color={colors.textLight} style={{ lineHeight: 22 }}>
              By accessing, downloading, or using the SpendWise mobile application, you agree to be bound by these Terms of Service. If you do not agree to all the terms, you may not access the services.
            </Typo>
          </View>

          <View style={styles.section}>
            <Typo size={18} fontWeight="700" color={colors.text}>
              2. Financial Disclaimer (Not Professional Advice)
            </Typo>
            <Typo size={14} color={colors.textLight} style={{ lineHeight: 22 }}>
              The information, analysis, and AI-generated responses provided by SpendWise are strictly for educational and informational purposes only. SpendWise is NOT a certified financial planner, investment advisor, or legal/tax professional.
              {"\n\n"}Any financial insights or budgeting suggestions generated by our AI should not be construed as professional financial advice. You are solely responsible for your financial decisions.
            </Typo>
          </View>

          <View style={styles.section}>
            <Typo size={18} fontWeight="700" color={colors.text}>
              3. User Responsibilities & Acceptable Use
            </Typo>
            <Typo size={14} color={colors.textLight} style={{ lineHeight: 22 }}>
              When using our Services, you agree not to:
              {"\n"}• Use the Services for any illegal or unauthorized purpose.
              {"\n"}• Attempt to reverse-engineer, decompile, or hack the application or its AI models.
              {"\n"}• Upload receipts or images that contain malicious code, highly sensitive illicit material, or content that violates third-party rights.
              {"\n"}• Abuse the AI chat feature by spamming or attempting to bypass safety filters.
            </Typo>
          </View>

          <View style={styles.section}>
            <Typo size={18} fontWeight="700" color={colors.text}>
              4. Intellectual Property & Trademark
            </Typo>
            <Typo size={14} color={colors.textLight} style={{ lineHeight: 22 }}>
              The SpendWise name, logo, and all related names, logos, product and service names, designs, and slogans are trademarks of SpendWise. All original content, features, and functionality within the app (including custom UI designs, AI prompt architectures, and software code) are owned by SpendWise.
            </Typo>
          </View>

          <View style={styles.section}>
            <Typo size={18} fontWeight="700" color={colors.text}>
              5. Contact Us
            </Typo>
            <Typo size={14} color={colors.textLight} style={{ lineHeight: 22 }}>
              If you have any questions about these Terms, licensing, or trademark inquiries, please contact our legal department at:
              {"\n"}spendwiseoffical@gmail.com
            </Typo>
          </View>
        </ScrollView>
      </View>
    </ModalWrapper>
  );
};

export default TermsOfServiceModal;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: spacingX._20,
  },
  content: {
    gap: spacingY._15,
    paddingBottom: spacingY._20,
  },
  section: {
    gap: spacingY._5,
  },
});
